// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPVqgJct9pclLwHaOpl6jWCwHWlYsd6Pc',
    appId: '1:688646268629:web:3570a44e0d33fe33f4645c',
    messagingSenderId: '688646268629',
    projectId: 'talktandem',
    authDomain: 'talktandem.firebaseapp.com',
    storageBucket: 'talktandem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjtxvpbWT8xyg965DFQ50Km8viAbBDg9w',
    appId: '1:688646268629:android:66af8eac2f15731df4645c',
    messagingSenderId: '688646268629',
    projectId: 'talktandem',
    storageBucket: 'talktandem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7Y-nOV770vEXvkHHJsy2Wtp9Tk-0A8M',
    appId: '1:688646268629:ios:6773e87994c01a9ff4645c',
    messagingSenderId: '688646268629',
    projectId: 'talktandem',
    storageBucket: 'talktandem.firebasestorage.app',
    iosBundleId: 'com.example.dosttConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX7Y-nOV770vEXvkHHJsy2Wtp9Tk-0A8M',
    appId: '1:688646268629:ios:6773e87994c01a9ff4645c',
    messagingSenderId: '688646268629',
    projectId: 'talktandem',
    storageBucket: 'talktandem.firebasestorage.app',
    iosBundleId: 'com.example.dosttConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPVqgJct9pclLwHaOpl6jWCwHWlYsd6Pc',
    appId: '1:688646268629:web:5041d6fbe54338cdf4645c',
    messagingSenderId: '688646268629',
    projectId: 'talktandem',
    authDomain: 'talktandem.firebaseapp.com',
    storageBucket: 'talktandem.firebasestorage.app',
  );
}
